### ISSUE TITLE
'postman' is missing.

### ISSUE THREAD

**Issue by brakmic** [jdubray/sam-samples#1]
Hi,

After having installed all npm packages I get this error. A local module './postman' is missing. There are several *postman modules on npm but I'm unsure if you're using one of them or if this is something from your code collection.

```msdos
D:\src\js\sam\sam-samples\crud-blog>node server
module.js:328
    throw err;
    ^

Error: Cannot find module './postman'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\src\js\sam\sam-samples\crud-blog\server.js:6:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
```

**Comment by jdubray** [comment]
I updated the code to make it optional

**Comment by brakmic** [comment]
Thanks :thumbsup:
